name: Tag pushed

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the tag name
      id: get_tag
      run: echo "The tag name is ${{ env.TAG_NAME }}"

    - name: Parse the tag name
      run: |
        echo "Parsing tag name: ${{ env.TAG_NAME }}"
        if echo ${{ env.TAG_NAME }} | grep -q '^staging_'; then
          echo "This is a staging tag"
          env_name = "Staging"
        elif echo ${{ env.TAG_NAME }} | grep -q '^production_'; then
          echo "This is a production tag"
          env_name = "Production"
        elif echo ${{ env.TAG_NAME }} | grep -q '^development_'; then
          echo "This is a development tag"
          env_name = "Development"
        else
          echo "This is not a valid tag"
          exit 1

    - name: Get project environment variables
      id: get_env_vars
      run: echo "::set-env name=ENV_NAME::$env_name"

    - name: Run command
      run: echo "Command"
      env:
        ENV_NAME: ${{ steps.get_env_vars.outputs.name }}

# Add jobs here
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env: 
      ENV: ${{ env.ENV_NAME }}
    steps:
    - name: Deploy to the environment
      run: echo "Deploying to $ENV"
